### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by ArktekniK** [ehd/node-ds4#6]
Hey, not a major problem but the x property should be 'cross'

**Comment by ArktekniK** [comment]
Also just noticed circle property is misspelt =)

**Comment by ehd** [comment]
Hey, I just published a new version of npm :smile: Someone fixed these a while ago, but I forgot to publish. README looking better now on npm?

**Comment by ArktekniK** [comment]
Heh, no the cricle property is still there in the dump on npm =)

**Comment by ehd** [comment]
Fixed now?

**Comment by ArktekniK** [comment]
Yep looks good, thanks
