### ISSUE TITLE
sh get-hidapi.sh

### ISSUE THREAD

**Issue by ArktekniK** [ehd/node-ds4#7]
During pre-install on Windows:

> node-hid@0.3.2 preinstall C:\Users\gbstarkeyr\AppData\Roaming\npm\node_modules\ds4\node_modules\node-hid
> sh get-hidapi.sh

'sh' is not recognized as an internal or external command.

Does this module work for Windows?

**Comment by ArktekniK** [comment]
I assume this is an issue with node-hid?

**Comment by ehd** [comment]
@ArktekniK It looks like the version of node-hid we're using doesn't support windows yet, but they're saying they do support windows now: https://github.com/node-hid/node-hid#prerequisites – Could you try updating the version in package.json?

**Comment by ehd** [comment]
Yes :smile:

**Comment by ArktekniK** [comment]
Cloned and updated deps.

````
"dependencies": {
    "lodash": "~2.4.0",
    "node-hid": "~0.5.1",
    "optimist": "~0.6.0"
  },
````
From the root dir, installed with ````npm install -g .```` but getting module not found when I try to require it...

````
C:\Git\rstarkey\node-ds4>npm install -g .
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN engine node-hid@0.5.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.0","npm":"2.5.1"})

> node-hid@0.5.1 install C:\Users\gbstarkeyr\AppData\Roaming\npm\node_modules\ds4\node_modules\node-hid
> node-pre-gyp install --fallback-to-build

[node-hid] Success: "C:\Users\gbstarkeyr\AppData\Roaming\npm\node_modules\ds4\node_modules\node-hid\build\HID\v0.5.1\Release\node-v14-win32-x64\HID.node" is installed via remote
C:\Users\gbstarkeyr\AppData\Roaming\npm\ds4-dump -> C:\Users\gbstarkeyr\AppData\Roaming\npm\node_modules\ds4\bin\ds4-dump.js
ds4@0.2.0 C:\Users\gbstarkeyr\AppData\Roaming\npm\node_modules\ds4
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── lodash@2.4.2
└── node-hid@0.5.1 (nan@2.1.0)
````

Checked out my global directory and I can see it in there :/

Any ideas?

**Comment by ArktekniK** [comment]
Updated and managed to get this working. I was trying to get it working under Electron shell, but the ABI version didn't match.

The samples work though so I'll consider this an issue on my end and close.

Thanks
