### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by batm4n** [ehd/node-ds4#8]
```
$ npm install -g ds4
```

fails. prints errors for node-hid

```console
2 warnings generated.
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:50:79: error: no member named 'New' in 'v8::String'
  virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
```
and exits on 20 errors.

**Comment by HaydenStanko** [comment]
Exact same thing here, would love a solution!

**Comment by ehd** [comment]
Whoop, which node versions are you using?

**Comment by batm4n** [comment]
node v4.3.1
also tested on v5.7.0

**Comment by ThodorisElissaios** [comment]
same here

**Comment by ehd** [comment]
Hey people, I'll try to fix this for 5.x this weekend :smile:

**Comment by seidtgeist** [comment]
@batm4n @HaydenStanko @ThodorisElissaios I removed some dependencies and bumped node-hid to latest. Installed successfully on latest node 5.x and should also work with relevant prior versions. Could you please give it a try? I didn't have a controller at hand :sob:

**Comment by seidtgeist** [comment]
Btw, the new version is 1.0.0-rc1 and published on npm as latest.

**Comment by mikkmartin** [comment]
awesome! will test as soon as i get my controller

**Comment by mikkmartin** [comment]
success!

**Comment by seidtgeist** [comment]
@batm4n Thanks for testing!
